name: "avionmqtt"
slug: "avionmqtt"
description: "Avi-on / Halo Home BLE → MQTT bridge"
version: "0.1.0"

startup: services
boot: auto
init: false
host_dbus: true
#privileged: true

# Give access to Bluetooth adapter device nodes
devices:
  - /dev/bus/usb
  - /dev/hci0

# Minimum capabilities that commonly matter for BLE
capabilities:
  - NET_ADMIN
  - NET_RAW

arch:
  - amd64

host_network: true

map:
  - type: homeassistant_config
    path: /config
    read_only: false

#options:
#  log_level: INFO

#schema:
#  log_level: list(DEBUG|INFO|WARNING|ERROR)
