name: avionmqtt
slug: avionmqtt
description: Avi-on / Halo Home BLE → MQTT bridge
version: "0.1.0"
startup: services
boot: auto
host_network: true
map:
  - config:rw
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
options:
  log_level: INFO
schema:
  log_level: list(DEBUG|INFO|WARNING|ERROR)
